package com.raven.main;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 * Example data-access methods that demonstrate how every query is filtered by
 * {@code user_id}. These are patterns you can reuse for assets, liabilities,
 * equity, journals, and reports.
 */
public class AccountingRepository {

    /**
     * Insert an asset row for the current user.
     */
    public void insertAsset(String name, double amount) throws SQLException {
        Integer userId = Session.getCurrentUserId();
        if (userId == null) {
            throw new IllegalStateException("No logged-in user in Session.");
        }

        String sql = "INSERT INTO assets (user_id, name, amount) VALUES (?, ?, ?)";
        try (Connection conn = DBConnection.connect();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setInt(1, userId);
            ps.setString(2, name);
            ps.setDouble(3, amount);
            ps.executeUpdate();
        }
    }

    /**
     * Example: get total assets for the current user.
     */
    public double getTotalAssetsForCurrentUser() throws SQLException {
        Integer userId = Session.getCurrentUserId();
        if (userId == null) {
            throw new IllegalStateException("No logged-in user in Session.");
        }

        String sql = "SELECT COALESCE(SUM(amount), 0) AS total_amount " +
                     "FROM assets WHERE user_id = ?";
        try (Connection conn = DBConnection.connect();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setInt(1, userId);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    return rs.getDouble("total_amount");
                }
                return 0.0;
            }
        }
    }

    /**
     * Example: insert a journal entry for the current user.
     */
    public void insertJournalEntry(String entryDate,
                                   String description,
                                   String debitAccount,
                                   String creditAccount,
                                   double amount) throws SQLException {
        Integer userId = Session.getCurrentUserId();
        if (userId == null) {
            throw new IllegalStateException("No logged-in user in Session.");
        }

        String sql = """
                INSERT INTO journal_entries
                    (user_id, entry_date, description, debit_account, credit_account, amount)
                VALUES (?, ?, ?, ?, ?, ?)
                """;

        try (Connection conn = DBConnection.connect();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setInt(1, userId);
            ps.setString(2, entryDate);
            ps.setString(3, description);
            ps.setString(4, debitAccount);
            ps.setString(5, creditAccount);
            ps.setDouble(6, amount);
            ps.executeUpdate();
        }
    }

    /**
     * Example: count reports generated by the current user.
     */
    public int countReportsForCurrentUser() throws SQLException {
        Integer userId = Session.getCurrentUserId();
        if (userId == null) {
            throw new IllegalStateException("No logged-in user in Session.");
        }

        String sql = "SELECT COUNT(*) AS cnt FROM reports WHERE user_id = ?";
        try (Connection conn = DBConnection.connect();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setInt(1, userId);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    return rs.getInt("cnt");
                }
                return 0;
            }
        }
    }
}

